--- #YAML:1.0
name:               DBD-IngresII
version:            0.89
abstract:           DBI driver for Actian Ingres and Actian Vectorwise RDBMS
author:
    - Henrik Tougaard (htoug@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config:  0
    DBI:     0
resources:
    repository:  http://dbdingresii.codeplex.com
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
