---
abstract: 'DBI driver for Actian Ingres and Actian Vectorwise RDBMS'
author:
  - 'Henrik Tougaard (htoug@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBD-IngresII
no_index:
  directory:
    - t
    - inc
requires:
  Config: 0
  DBI: 0
resources:
  repository: http://chiselapp.com/user/xenu/repository/dbd-ingresii
version: 0.93
